config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  resources :userposts
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  devise_for :users
  get 'profile/index'
  get 'home/introduction'
  get 'home/index'
  root  'home#index'
  post 'post/:post_id/like' => 'posts#like_toggle'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/poll.rb
class Poll < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, S3Uploader
    belongs_to :user
    has_many :comments
    has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :likes

  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/models/userpost.rb
class Userpost < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment=Comment.new(comment_params)
    @comment.post_id=params[:post_id]
    @comment.save

    redirect_to "/posts/#{params[:post_id]}"  
  end

  def destroy
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.order(:created_at => :desc).page(params[:page])

  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:image, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to '/profile/index', notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like_toggle
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    #좋아요가 눌렸는지 체크
    if like.nil?
      Like.create(user_id: current_user.id, post_id: params[:post_id])
    else
      like.destroy
    end
    redirect_to "/posts/#{params[:post_id]}"
  end

  skip_before_filter :verify_authenticity_token


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:image, :content, :user_id)
    end


end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts=Post.where(user_id:current_user.id)
  
  end
end

app/controllers/userposts_controller.rb
class UserpostsController < ApplicationController
  before_action :set_userpost, only: [:show, :edit, :update, :destroy]

  # GET /userposts
  # GET /userposts.json
  def index
    @userposts = Userpost.all
  end

  # GET /userposts/1
  # GET /userposts/1.json
  def show
  end

  # GET /userposts/new
  def new
    @userpost = Userpost.new
  end

  # GET /userposts/1/edit
  def edit
  end

  # POST /userposts
  # POST /userposts.json
  def create
    @userpost = Userpost.new(userpost_params)

    respond_to do |format|
      if @userpost.save
        format.html { redirect_to @userpost, notice: 'Userpost was successfully created.' }
        format.json { render :show, status: :created, location: @userpost }
      else
        format.html { render :new }
        format.json { render json: @userpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userposts/1
  # PATCH/PUT /userposts/1.json
  def update
    respond_to do |format|
      if @userpost.update(userpost_params)
        format.html { redirect_to @userpost, notice: 'Userpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @userpost }
      else
        format.html { render :edit }
        format.json { render json: @userpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userposts/1
  # DELETE /userposts/1.json
  def destroy
    @userpost.destroy
    respond_to do |format|
      format.html { redirect_to userposts_url, notice: 'Userpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userpost
      @userpost = Userpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userpost_params
      params.require(:userpost).permit(:image, :content, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/userposts_helper.rb
module UserpostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cola</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
     <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
     <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata|Unica+One" rel="stylesheet">
  </head>

  <body>
  
   <nav class="nav">
      <div class="nav-wrapper">
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="/">MAIN</a></li>
          <li><a href='/profile/index'>PROFILE</a></li>
          <% if user_signed_in? %>
          <li>
           <%= link_to('LOGOUT', destroy_user_session_path, method: :delete) %>        
          </li>
          <% else %>
          <li>
          <%= link_to('LOGIN', new_user_session_path)  %>  
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
   
    <%= yield %>
  </body>
</html>

app/views/polls/_form.html.erb
<%= form_for(poll) do |f| %>
  <% if poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% poll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polls/_poll.html.erb
<tr class="polls"> <td><%= poll.image %></td> <td><%= poll.content %></td> <td><%= link_to 'Show', poll %></td> <td><%= link_to 'Edit', edit_poll_path(poll) %></td> <td><%= link_to 'Destroy', poll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/polls/edit.html.erb
<h1>Editing Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Polls</h1>
<h1>Listing posts</h1>
<table class="polls"> <thead> <tr> <th>Title</th> <th>Body</th> <th colspan="3"></th> </tr> </thead>
<tbody class="page"> <%= render @polls %> </tbody>
</table>
<br>
<%= link_to 'New Poll', new_poll_path %>
<%= paginate @polls %>

app/views/polls/index.js.erb
$(".polls").append("<tbody class='page'><%= escape_javascript(render(@polls)) %></tbody>");

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form', poll: @poll %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @poll.image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @poll.content %>
</p>

<%= link_to 'Edit', edit_poll_path(@poll) %> |
<%= link_to 'Back', polls_path %>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field cc">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  
  <div class="fileinput fileinput-new" data-provides="fileinput">
    <div class="post-new-bar">
      <%= f.file_field  :image, class: "a", accept: 'image/png,image/gif,image/jpeg' %>
      <span class="post-new-bar-remove">
      <a href="#" class="b" data-dismiss="fileinput">Remove</a></span>
    </div>
    <div class="fileinput-preview fileinput-exists thumbnail dd" style="width: 600px; height:auto;"></div>
    
  </div>

  <div class="actions">
    <%= f.submit "Create", class: "post-new-bar-create"%>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<br><br>

 

<div class="grid-container">
    <% @posts.each do |post| %>
   
        <td><%= link_to image_tag(post.image), post, class:"grid-item" %></td>
    
    <% end %>
</div>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class="post-new">
<h1>New Post</h1>

<%= render 'form', post: @post %>

</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
    <p>
      <strong>Like:</strong>
      <%= @post.likes.size %> 명이 좋아합니다. 
    </p>
     

      <% if current_user.is_like?(@post)%>
      <form action='/post/<%= @post.id%>/like' method='post'>
      <button> 좋아요 취소 </button>  
      </form>
      
      <% else %>
      <form action='/post/<%= @post.id%>/like' method='post'>
      <button> 좋아요</button>  
      </form>
      
      <% end %>
  
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<%=form_for Comment.new, url:post_comments_path(@post.id) do |f|%>
<%=f.label "댓글"%>
<%=f.text_field :content%><br>
<%=f.submit "작성"%>
<%end%>
<%@post.comments.each do |comment|%>
  <%=comment.content%> <%= link_to '[댓글 삭제]',
    post_comment_path(@post.id,comment.id),method: 'delete'%><br>
<%end%>

app/views/userposts/_form.html.erb
<%= form_for(userpost) do |f| %>
  <% if userpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(userpost.errors.count, "error") %> prohibited this userpost from being saved:</h2>

      <ul>
      <% userpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/userposts/edit.html.erb
<h1>Editing Userpost</h1>

<%= render 'form', userpost: @userpost %>

<%= link_to 'Show', @userpost %> |
<%= link_to 'Back', userposts_path %>

app/views/userposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Userposts</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userposts.each do |userpost| %>
      <tr>
        <td><%= userpost.image %></td>
        <td><%= userpost.content %></td>
        <td><%= userpost.user %></td>
        <td><%= link_to 'Show', userpost %></td>
        <td><%= link_to 'Edit', edit_userpost_path(userpost) %></td>
        <td><%= link_to 'Destroy', userpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userpost', new_userpost_path %>

app/views/userposts/new.html.erb
<h1>New Userpost</h1>

<%= render 'form', userpost: @userpost %>

<%= link_to 'Back', userposts_path %>

app/views/userposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @userpost.image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @userpost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @userpost.user %>
</p>

<%= link_to 'Edit', edit_userpost_path(@userpost) %> |
<%= link_to 'Back', userposts_path %>